### ISSUE TITLE
Where is start.bat?

### ISSUE THREAD

**Issue by James-Sangalli** [NEST-Protocol/NEST-oracle-V3-miner#2]
I can only find mvnw.bat & mvnw sh file

Running mvnw on mac requires a command like `deploy` although I am not sure what command to use.

When I run this program I do so by invoking ibApplication.java, is this the way that you recommend it too?

**Comment by wll2143** [comment]
The start.bat file is in the NEST- Oracle-V3-Miner. Zip release package
